name: flutter_staggered_grid_view
description: Provides a collection of Flutter grids layouts (staggered, masonry, quilted, woven, etc.).
version: 0.7.0
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.7.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter